// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {context} from '../models';
import {app} from '../models';
import {session} from '../models';
import {intercept} from '../models';
import {adapter} from '../models';

export function AddRule(arg1:model.Rule):Promise<void>;

export function BreakpointDrop(arg1:string):Promise<void>;

export function BreakpointResume(arg1:string):Promise<void>;

export function ClearSessions():Promise<void>;

export function DisableSystemProxy():Promise<void>;

export function EnableSystemProxy():Promise<void>;

export function ExportCA(arg1:string):Promise<void>;

export function ExportSessionsHAR():Promise<void>;

export function ExportSessionsJSON():Promise<void>;

export function ExportSessionsSAZ():Promise<void>;

export function GetCAInfo():Promise<model.CAInfo>;

export function GetContext():Promise<context.Context>;

export function GetPendingBreakpoints():Promise<Array<app.BreakpointPending>>;

export function GetProxyState():Promise<string>;

export function GetSessions():Promise<Array<model.Session>>;

export function GetSessionsFiltered(arg1:model.SessionFilter):Promise<Array<model.Session>>;

export function HandleNewSession(arg1:model.Session):Promise<void>;

export function ImportSessionsSAZ():Promise<number>;

export function InstallCA():Promise<void>;

export function IsSystemProxyActive():Promise<boolean>;

export function ListRules():Promise<Array<model.Rule>>;

export function RemoveRule(arg1:string):Promise<void>;

export function SendRequest(arg1:app.ComposerRequest):Promise<app.ComposerResponse>;

export function SetAutoSaver(arg1:session.AutoSaver):Promise<void>;

export function SetBreakpoint(arg1:intercept.Breakpoint):Promise<void>;

export function SetEngine(arg1:adapter.ProxyEngine):Promise<void>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;

export function ToggleRule(arg1:string):Promise<void>;

export function UninstallCA():Promise<void>;
