// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSessions() {
  return window['go']['app']['App']['ClearSessions']();
}

export function GetProxyState() {
  return window['go']['app']['App']['GetProxyState']();
}

export function GetSessions() {
  return window['go']['app']['App']['GetSessions']();
}

export function HandleNewSession(arg1) {
  return window['go']['app']['App']['HandleNewSession'](arg1);
}

export function SetEngine(arg1) {
  return window['go']['app']['App']['SetEngine'](arg1);
}

export function StartProxy() {
  return window['go']['app']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['app']['App']['StopProxy']();
}
