// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {intercept} from '../models';
import {context} from '../models';
import {app} from '../models';
import {session} from '../models';
import {adapter} from '../models';
import {throttle} from '../models';

export function AddRule(arg1:model.Rule):Promise<void>;

export function BreakpointDrop(arg1:string):Promise<void>;

export function BreakpointResume(arg1:string):Promise<void>;

export function BreakpointResumeWithEdit(arg1:string,arg2:intercept.EditedRequest):Promise<void>;

export function CAInfo():Promise<model.CAInfo>;

export function ClearSessions():Promise<void>;

export function CommentSession(arg1:string,arg2:string):Promise<void>;

export function Context():Promise<context.Context>;

export function DisableSystemProxy():Promise<void>;

export function EnableSystemProxy():Promise<void>;

export function ExportCA(arg1:string):Promise<void>;

export function ExportSessionsHAR():Promise<void>;

export function ExportSessionsJSON():Promise<void>;

export function ExportSessionsSAZ():Promise<void>;

export function HandleNewSession(arg1:model.Session):Promise<void>;

export function ImportSessionsHAR():Promise<number>;

export function ImportSessionsSAZ():Promise<number>;

export function InstallCA():Promise<void>;

export function IsSystemProxyActive():Promise<boolean>;

export function ListRules():Promise<Array<model.Rule>>;

export function LoadSessions():Promise<number>;

export function PendingBreakpoints():Promise<Array<app.BreakpointPending>>;

export function ProxyState():Promise<string>;

export function RemoveRule(arg1:string):Promise<void>;

export function ReplaySession(arg1:string):Promise<app.ComposerResponse>;

export function SaveSessions():Promise<void>;

export function SendRequest(arg1:app.ComposerRequest):Promise<app.ComposerResponse>;

export function Sessions():Promise<Array<model.Session>>;

export function SessionsFiltered(arg1:model.SessionFilter):Promise<Array<model.Session>>;

export function SetAutoSaver(arg1:session.AutoSaver):Promise<void>;

export function SetBreakpoint(arg1:intercept.Breakpoint):Promise<void>;

export function SetEngine(arg1:adapter.ProxyEngine):Promise<void>;

export function SetThrottle(arg1:string):Promise<void>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;

export function TagSession(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ThrottleState():Promise<app.ThrottleConfig>;

export function Throttler():Promise<throttle.Throttler>;

export function ToggleRule(arg1:string):Promise<void>;

export function UninstallCA():Promise<void>;
