// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {adapter} from '../models';

export function ClearSessions():Promise<void>;

export function GetProxyState():Promise<string>;

export function GetSessions():Promise<Array<model.Session>>;

export function HandleNewSession(arg1:model.Session):Promise<void>;

export function SetEngine(arg1:adapter.ProxyEngine):Promise<void>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;
