// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRule(arg1) {
  return window['go']['app']['App']['AddRule'](arg1);
}

export function BreakpointDrop(arg1) {
  return window['go']['app']['App']['BreakpointDrop'](arg1);
}

export function BreakpointResume(arg1) {
  return window['go']['app']['App']['BreakpointResume'](arg1);
}

export function BreakpointResumeWithEdit(arg1, arg2) {
  return window['go']['app']['App']['BreakpointResumeWithEdit'](arg1, arg2);
}

export function CAInfo() {
  return window['go']['app']['App']['CAInfo']();
}

export function ClearSessions() {
  return window['go']['app']['App']['ClearSessions']();
}

export function CommentSession(arg1, arg2) {
  return window['go']['app']['App']['CommentSession'](arg1, arg2);
}

export function Context() {
  return window['go']['app']['App']['Context']();
}

export function DisableSystemProxy() {
  return window['go']['app']['App']['DisableSystemProxy']();
}

export function EnableSystemProxy() {
  return window['go']['app']['App']['EnableSystemProxy']();
}

export function ExportCA(arg1) {
  return window['go']['app']['App']['ExportCA'](arg1);
}

export function ExportSessionsHAR() {
  return window['go']['app']['App']['ExportSessionsHAR']();
}

export function ExportSessionsJSON() {
  return window['go']['app']['App']['ExportSessionsJSON']();
}

export function ExportSessionsSAZ() {
  return window['go']['app']['App']['ExportSessionsSAZ']();
}

export function HandleNewSession(arg1) {
  return window['go']['app']['App']['HandleNewSession'](arg1);
}

export function ImportSessionsHAR() {
  return window['go']['app']['App']['ImportSessionsHAR']();
}

export function ImportSessionsSAZ() {
  return window['go']['app']['App']['ImportSessionsSAZ']();
}

export function InstallCA() {
  return window['go']['app']['App']['InstallCA']();
}

export function IsSystemProxyActive() {
  return window['go']['app']['App']['IsSystemProxyActive']();
}

export function ListRules() {
  return window['go']['app']['App']['ListRules']();
}

export function LoadSessions() {
  return window['go']['app']['App']['LoadSessions']();
}

export function PendingBreakpoints() {
  return window['go']['app']['App']['PendingBreakpoints']();
}

export function ProxyState() {
  return window['go']['app']['App']['ProxyState']();
}

export function RemoveRule(arg1) {
  return window['go']['app']['App']['RemoveRule'](arg1);
}

export function ReplaySession(arg1) {
  return window['go']['app']['App']['ReplaySession'](arg1);
}

export function SaveSessions() {
  return window['go']['app']['App']['SaveSessions']();
}

export function SendRequest(arg1) {
  return window['go']['app']['App']['SendRequest'](arg1);
}

export function Sessions() {
  return window['go']['app']['App']['Sessions']();
}

export function SessionsFiltered(arg1) {
  return window['go']['app']['App']['SessionsFiltered'](arg1);
}

export function SetAutoSaver(arg1) {
  return window['go']['app']['App']['SetAutoSaver'](arg1);
}

export function SetBreakpoint(arg1) {
  return window['go']['app']['App']['SetBreakpoint'](arg1);
}

export function SetEngine(arg1) {
  return window['go']['app']['App']['SetEngine'](arg1);
}

export function SetThrottle(arg1) {
  return window['go']['app']['App']['SetThrottle'](arg1);
}

export function StartProxy() {
  return window['go']['app']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['app']['App']['StopProxy']();
}

export function TagSession(arg1, arg2, arg3) {
  return window['go']['app']['App']['TagSession'](arg1, arg2, arg3);
}

export function ThrottleState() {
  return window['go']['app']['App']['ThrottleState']();
}

export function Throttler() {
  return window['go']['app']['App']['Throttler']();
}

export function ToggleRule(arg1) {
  return window['go']['app']['App']['ToggleRule'](arg1);
}

export function UninstallCA() {
  return window['go']['app']['App']['UninstallCA']();
}
